### ISSUE TITLE
"Failed to execute 'decodeAudioData' on 'BaseAudioContext': Unable to decode audio data"

### ISSUE THREAD

**Issue by mikey88** [lubenard/simple-mp3-cutter#4]
Hi :-) Happening in latest version of Chrome. 

Uncaught (in promise) ReferenceError: Mp3LameEncoder is not defined
    at mp3cutter.computeData (cutter.js:63:17)
    at cutter.js:42:72

**Comment by ghost** [comment]
install the Mp3LameEncoder library. If it does not work, edit the source in cutter.js
